#!/usr/bin/env bash
# Checks if there are 4 parameters and transfer the file using SCP
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -i "$4" "$1" "$3"@"$2":~/
