#!/usr/bin/env bash
# This script installs and configures nginx to serve "Hello World!" at the root
apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
