#!/usr/bin/env bash
# Nginx configuration for redirection
echo 'server {
    listen 80;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}' > /etc/nginx/sites_available/default
service nginx reload
