#!/usr/bin/env bash
# This script is creating the file /var/run/myscript.pid containing its PID, displaying To infinity and beyond indefinitely, "I hate the kill command" when receiving a SIGTERM signal, "Y U no love me?!" when receiving a SIGINT signal, and deleting the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal.

touch /var/run/myscript.pid
echo "$$" > /var/run/myscript.pid
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap  "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM
while true; do
	echo "To infinity and beyond"
	((count++))
done
