#!/usr/bin/env bash
# This script is displaying the PID, along with the process name, of processes whose name contain the word bash.

for prc in /proc/*/cmdline; { (printf "$prc "; cat -A "$prc") | sed 's/\^@/ /g;s|/proc/||;s|/cmdline||'; echo; } | grep bash
