#!/usr/bin/env bash
# Returns a page containing Hello ALX when querying the root of it.

docker build -t alx/265-0 .
docker rm -f first_container
docker run -p 8080:80 -d --name first_container alx/265-0

sleep 3

docker exec first_container apachectl status | grep "Apache Server Status" && echo "apache2 is running"
